language: ruby

rvm:
  - 2.3.1

before_script:
  - cd blog
  - bundle install --jobs=3 --retry=3

script: 
  - rails test
  - rails cucumber

after_success:
  - coveralls --exclude app/channels/application_cable/ --exclude app/mailers/ --exclude app/models/application_record.rb --gcov-options '\-lp'
